name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Day 1 Exercise 1
        id: D1E1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D1E1
          setup-command: ''
          command: './mvnw test -Dtest=D1E1Tests'
          timeout: 1
          max-score: 1

      - name: Day 1 Exercise 2
        id: D1E2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D1E2
          setup-command: ''
          command: './mvnw test -Dtest=D1E2Tests'
          timeout: 1
          max-score: 1

      - name: Day 1 Exercise 3
        id: D1E3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D1E3
          setup-command: ''
          command: './mvnw test -Dtest=D1E3Tests'
          timeout: 1
          max-score: 1

      - name: Day 2 Exercise 1
        id: D2E1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D2E1
          setup-command: ''
          command: './mvnw test -Dtest=D2E1Tests'
          timeout: 1
          max-score: 1

      - name: Day 2 Exercise 2
        id: D2E2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D2E2
          setup-command: ''
          command: './mvnw test -Dtest=D2E2Tests'
          timeout: 1
          max-score: 1

      - name: Day 2 Exercise 3
        id: D2E3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D2E3
          setup-command: ''
          command: './mvnw test -Dtest=D2E3Tests'
          timeout: 1
          max-score: 1

      - name: Day 3 Exercise 1
        id: D3E1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D3E1
          setup-command: ''
          command: './mvnw test -Dtest=D3E1Tests'
          timeout: 1
          max-score: 1

      - name: Day 3 Exercise 2
        id: D3E2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: D3E2
          setup-command: ''
          command: './mvnw test -Dtest=D3E2Tests'
          timeout: 1
          max-score: 1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          D1E1_RESULTS: '${{steps.D1E1.outputs.result}}'
          D1E2_RESULTS: '${{steps.D1E2.outputs.result}}'
          D1E3_RESULTS: '${{steps.D1E3.outputs.result}}'
          D2E1_RESULTS: '${{steps.D2E1.outputs.result}}'
          D2E2_RESULTS: '${{steps.D2E2.outputs.result}}'
          D2E3_RESULTS: '${{steps.D2E3.outputs.result}}'
          D3E1_RESULTS: '${{steps.D3E1.outputs.result}}'
          D3E2_RESULTS: '${{steps.D3E2.outputs.result}}'
        with:
          runners: D1E1,D1E2,D1E3,D2E1,D2E2,D2E3,D3E1,D3E2
